# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: lint-check
description: "Check Project for Linting Errors"

runs:
  using: composite
  steps:
    - name: Lint Deps
      run: GOPATH="$HOME/go" go install github.com/google/addlicense@v1.1.1
      shell: bash

    - name: Run License Linting Checks
      run: uds run license --no-progress
      shell: bash
